[package]
name = "vifsim"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/adclz/vif-sim/tree/main"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.37"
serde-wasm-bindgen = "0.6.0"
js-sys = "0.3.64"
web-sys = { version = "0.3.66", features = ["BroadcastChannel"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.26", features = ["wasmbind"] }
camelpaste = "0.1.0"
console_error_panic_hook = "0.1.7"
tsify = "0.4.5"
tokio = { version = "1.35.1", features = ["sync", "time"] }
futures = "0.3.28"
once_cell = "1.18.0"
web-time = "0.2.3"
enum_dispatch = "0.3.12"
smart-default = "0.7.1"
gloo-timers = { version = "0.3.0", features = ["futures"] }
ansi_term = "0.12.1"
uuid = { version ="1.6.1", features = ["v4", "js"] }
fixedstr = { version = "0.5.5" }
nohash-hasher = "0.2.0"
bimap = "0.6.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
spin_sleep = "1.2.0"
pollster = { version = "0.3.0", features = ["macro"] }

[lib]
crate-type = ["cdylib", "lib"]
name = "vifsimlib"
path = "src/lib.rs"

[[bin]]
name = "vifsim"
path = "src/main.rs"

[features]
node = []


